fix: buggy max by sorting for liquidity among pools
Uniswap/smart-order-router pull request #300
Opened 2023-08-10 20:52 UTC by zhongeric

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **What is the current behavior?** (You can also link to an open issue here)

- **What is the new behavior (if this is a feature change)?**

- **Other information**:

2023-08-10 20:55 UTC, mikeki submitted a review, later dismissed

2023-08-10 21:02 UTC, jsy1218 commented
routing-api team discussed to start adding more unit test coverage against [smart-order-router](https://github.com/Uniswap/smart-order-router). This seems like a good use of it. I think the team can add it as a fast follow-up, so that we don't block merging this PR. It's probably affecting many v3 route.

2023-08-10 21:02 UTC, jsy1218 submitted a review, later dismissed

2023-08-10 21:05 UTC, rileydcampbell submitted a review, later dismissed

2023-08-11 20:47 UTC, mikeki approved these changes

2023-08-11 20:50 UTC, jsy1218 submitted a review, later dismissed

2023-08-11 20:53 UTC, mikeki requested changes
Sorry, taking back the previous approval.

I was wondering if you have a test case that is targetted towards the specific bug that you just solved.

One that would return the incorrect pool when using the `maxBy` method and the right pool when using your bug fix.

2023-08-11 20:53 UTC, mikeki commented on test/unit/routers/alpha-router/util/gas-factory-helpers.test.ts
> +describe.only('getHighestLiquidity pool tests', () => {
`.only` here

2023-08-11 21:53 UTC, mikeki approved these changes

2023-08-11 21:55 UTC, merged